import { CirclePlus, Pencil, Plus, Trash2 } from 'lucide-react'
import type { Filter, Holding } from '../types/portfolio'
import { hasOpeningTransaction } from '../utils/transactionCalculations'
import type { Transaction } from '../types/transaction'
import { PortfolioFilter } from './PortfolioFilter'

const categoryLabel = { investment: '투자', allowance: '용돈', pension: '연금' }
const money = (value: number, currency: Holding['currency']) => currency === 'USD' ? `$${value.toLocaleString('en-US', { maximumFractionDigits: 2 })}` : `${value.toLocaleString('ko-KR')}원`

export function HoldingsManagementView({ holdings, transactions, filter, onFilter, onAdd, onEdit, onDelete, onOpening }: { holdings: Holding[]; transactions: Transaction[]; filter: Filter; onFilter: (filter: Filter) => void; onAdd: () => void; onEdit: (holding: Holding) => void; onDelete: (holding: Holding) => void; onOpening: (holding: Holding) => void }) {
  const visible = holdings.filter(holding => filter === 'all' || holding.category === filter)
  return <section className="management-view"><header className="view-header"><div><h2>종목 관리</h2><p>보유 종목의 기본 정보와 거래 시작 상태를 관리합니다.</p></div><button className="add" onClick={onAdd}><Plus size={18} aria-hidden="true" /> 종목 추가</button></header><PortfolioFilter value={filter} onChange={onFilter} /><div className="management-list">{visible.map(holding => { const opened = hasOpeningTransaction(transactions, holding); const positionBased = Boolean(holding.transactionPosition); return <article className="management-row" key={holding.id}><div className="management-name"><b>{holding.displayName ?? holding.name}</b><span>{holding.market === 'KR' ? '국내' : '미국'} · {holding.symbol}{holding.exchange ? ` · ${holding.exchange}` : ''}</span><small>{categoryLabel[holding.category]}</small></div><div><label>보유수량</label><strong>{holding.quantity.toLocaleString()}주</strong></div><div><label>평균매수가</label><strong>{money(holding.averagePrice, holding.currency)}</strong></div><div><label>현재가</label><strong>{money(holding.currentPrice, holding.currency)}</strong><small className={`quote-status ${holding.priceStatus ?? 'fallback'}`}>{holding.priceStatus === 'live' ? '최신 시세' : holding.priceStatus === 'cached' ? '이전 시세' : '저장된 가격'}</small></div><div className="management-actions">{!opened && <button onClick={() => onOpening(holding)}><CirclePlus size={16} /> 초기 보유 등록</button>}{opened && <span className="opening-done">초기 보유 등록됨</span>}<button aria-label={`${holding.name} 수정`} onClick={() => onEdit(holding)}><Pencil size={16} /></button><button className="danger-icon" aria-label={`${holding.name} 삭제`} onClick={() => onDelete(holding)}><Trash2 size={16} /></button>{positionBased && <small className="position-note">거래내역 기반으로 자동 계산됩니다.</small>}</div></article> })}{!visible.length && <p className="empty-ledger">표시할 종목이 없습니다.</p>}</div></section>
}
