import { Monitor, Moon, RotateCcw, Sun } from 'lucide-react'
import type { Theme } from '../hooks/useTheme'
import type { MarketDataStatus } from '../types/portfolio'

const themeOptions: { value: Theme; label: string; icon: typeof Monitor }[] = [{ value: 'system', label: '시스템 설정', icon: Monitor }, { value: 'light', label: '라이트', icon: Sun }, { value: 'dark', label: '다크', icon: Moon }]
const rateStatus = (status?: MarketDataStatus) => status === 'live' ? '최신' : status === 'cached' ? '이전 값' : status === 'fallback' ? 'Fallback' : '확인 대기'

export function SettingsView({ theme, onTheme, onReset, updatedAt, exchangeRate }: { theme: Theme; onTheme: (theme: Theme) => void; onReset: () => void; updatedAt?: string; exchangeRate?: { status: MarketDataStatus; rate: number } }) {
  const updated = updatedAt ? new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(updatedAt)) : '아직 갱신하지 않음'
  return <section className="settings-view"><header className="view-header"><div><h2>설정</h2><p>화면 표시와 앱의 로컬 데이터를 관리합니다.</p></div></header><section className="settings-group"><h3>화면 설정</h3><div className="settings-row theme-row"><div><b>화면 모드</b><span>선택 즉시 전체 화면에 적용됩니다.</span></div><div className="theme-options" role="group" aria-label="화면 모드">{themeOptions.map(({ value, label, icon: Icon }) => <button key={value} className={theme === value ? 'active' : ''} onClick={() => onTheme(value)} aria-pressed={theme === value}><Icon size={16} aria-hidden="true" /> {label}</button>)}</div></div></section><section className="settings-group"><h3>시세 / 연동 상태</h3><div className="settings-row"><div><b>시세 갱신</b><span>수동</span></div><strong>정상</strong></div><div className="settings-row"><div><b>KIS 시세 연동</b><span>국내·미국 주식 시세</span></div><strong>정상</strong></div><div className="settings-row"><div><b>USD/KRW 환율</b><span>{exchangeRate ? `${exchangeRate.rate.toLocaleString('ko-KR')}원` : '조회 전'}</span></div><strong>{rateStatus(exchangeRate?.status)}</strong></div><div className="settings-row"><div><b>마지막 시세 갱신</b><span>{updated}</span></div></div></section><section className="settings-group"><h3>데이터 관리</h3><div className="settings-row danger-row"><div><b>모든 데이터 초기화</b><span>보유 종목과 거래내역을 모두 초기화합니다.</span></div><button onClick={onReset}><RotateCcw size={16} /> 초기화</button></div></section><section className="settings-group"><h3>앱 정보</h3><div className="settings-row"><div><b>앱 이름</b><span>나의 포트폴리오</span></div></div><div className="settings-row"><div><b>시세</b><span>한국투자증권 Open API</span></div></div><div className="settings-row"><div><b>시세 갱신 방식</b><span>수동 갱신</span></div></div></section></section>
}
