import { Pencil, Plus, Trash2, X } from 'lucide-react'
import type { Category, Filter, Market } from '../types/portfolio'
import type { Transaction } from '../types/transaction'
import { calculateSaleResults, realizedProfitSummary, transactionsForSymbol } from '../utils/transactionCalculations'

const won = (value: number) => `${new Intl.NumberFormat('ko-KR', { maximumFractionDigits: 0 }).format(Math.abs(value))}원`
const signedWon = (value: number) => `${value >= 0 ? '+' : '-'}${won(value)}`
const usd = (value: number) => `$${Math.abs(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const signedUsd = (value: number) => `${value >= 0 ? '+' : '-'}${usd(value)}`
const typeLabel = (type: Transaction['type']) => type === 'opening' ? '초기 보유' : type === 'buy' ? '매수' : '매도'
const categoryLabel: Record<Category, string> = { investment: '투자', allowance: '용돈', pension: '연금' }
export type TransactionScope = { market: Market; symbol: string; name: string }

export function TransactionLedger({ transactions, filter, scope, onFilter, onAdd, onEdit, onDelete, onClearScope }: { transactions: Transaction[]; filter: Filter; scope?: TransactionScope; onFilter: (filter: Filter) => void; onAdd: () => void; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void; onClearScope: () => void }) {
  const scoped = scope ? transactionsForSymbol(transactions, scope.market, scope.symbol) : transactions
  const visible = scoped.filter(transaction => filter === 'all' || transaction.category === filter).sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt))
  const summary = realizedProfitSummary(scoped, filter === 'all' ? undefined : filter)
  const saleResults = calculateSaleResults(scoped)
  return <section className="ledger"><div className="ledger-header"><div><p>{scope ? `${scope.name} · 거래내역` : '거래 원장'}</p><h2>{filter === 'all' ? '전체' : categoryLabel[filter]} 실현손익</h2><strong className={summary.krw === undefined ? '' : summary.krw >= 0 ? 'up' : 'down'}>{summary.krw === undefined ? '환율 정보 필요' : signedWon(summary.krw)}</strong>{summary.usd !== 0 && <small className={summary.usd >= 0 ? 'up' : 'down'}>미국주식 {signedUsd(summary.usd)}</small>}<em>앱 내부 포트폴리오 관리용 계산값입니다.</em></div><div className="ledger-actions">{scope && <button className="text-button" onClick={onClearScope}><X size={15} /> 전체 거래</button>}<button className="add transaction-add" onClick={onAdd}><Plus size={18} aria-hidden="true" /> 거래 추가</button></div></div><div className="filter transaction-filter" aria-label="거래내역 필터">{([['all', '전체'], ['investment', '투자'], ['allowance', '용돈'], ['pension', '연금']] as const).map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => onFilter(value)}>{label}</button>)}</div><div className="transaction-list">{visible.length ? visible.map(transaction => { const result = transaction.type === 'sell' ? saleResults.get(transaction.id) : undefined; return <article className="transaction-row" key={transaction.id}><div className="transaction-main"><time>{transaction.date.replaceAll('-', '.')} · {categoryLabel[transaction.category]}</time><b>{transaction.name} <span>{transaction.symbol}</span></b><p>{typeLabel(transaction.type)} {transaction.quantity.toLocaleString()}주 · {transaction.currency === 'USD' ? `$${transaction.price.toLocaleString('en-US')}` : `${transaction.price.toLocaleString('ko-KR')}원`}</p>{result && <small className={result.profit >= 0 ? 'up' : 'down'}>실현손익 {transaction.currency === 'USD' ? signedUsd(result.profit) : signedWon(result.profit)}</small>}{transaction.memo && <small>{transaction.memo}</small>}</div><div className="transaction-actions"><span>{typeLabel(transaction.type)}</span><button onClick={() => onEdit(transaction)} aria-label={`${transaction.name} 거래 수정`}><Pencil size={16} /></button><button className="danger-icon" onClick={() => onDelete(transaction)} aria-label={`${transaction.name} 거래 삭제`}><Trash2 size={16} /></button></div></article> }) : <p className="empty-ledger">표시할 거래가 없습니다.</p>}</div></section>
}
