import { Pencil, Plus, Trash2 } from 'lucide-react'
import type { Filter } from '../types/portfolio'
import type { Transaction } from '../types/transaction'
import { calculateSaleResults, realizedProfitSummary } from '../utils/transactionCalculations'

const won = (value: number) => `${new Intl.NumberFormat('ko-KR', { maximumFractionDigits: 0 }).format(Math.abs(value))}원`
const signedWon = (value: number) => `${value >= 0 ? '+' : '-'}${won(value)}`
const usd = (value: number) => `$${Math.abs(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const signedUsd = (value: number) => `${value >= 0 ? '+' : '-'}${usd(value)}`
const typeLabel = (type: Transaction['type']) => type === 'opening' ? '초기 보유' : type === 'buy' ? '매수' : '매도'

export function TransactionLedger({ transactions, filter, onFilter, onAdd, onEdit, onDelete }: { transactions: Transaction[]; filter: Filter; onFilter: (filter: Filter) => void; onAdd: () => void; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void }) {
  const visible = transactions.filter(transaction => filter === 'all' || transaction.category === filter).sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt))
  const summary = realizedProfitSummary(transactions, filter === 'all' ? undefined : filter)
  const saleResults = calculateSaleResults(transactions)
  return <section className="ledger"><div className="ledger-header"><div><p>거래 원장</p><h2>{filter === 'all' ? '전체' : filter === 'investment' ? '투자' : filter === 'allowance' ? '용돈' : '연금'} 실현손익</h2><strong className={summary.krw === undefined ? '' : summary.krw >= 0 ? 'up' : 'down'}>{summary.krw === undefined ? '환율 정보 필요' : signedWon(summary.krw)}</strong>{summary.usd !== 0 && <small className={summary.usd >= 0 ? 'up' : 'down'}>미국주식 {signedUsd(summary.usd)}</small>}<em>앱 내부 포트폴리오 관리용 계산값입니다.</em></div><button className="add transaction-add" onClick={onAdd}><Plus size={18} aria-hidden="true" /> 거래 추가</button></div><div className="filter transaction-filter" aria-label="거래내역 필터">{([['all', '전체'], ['investment', '투자'], ['allowance', '용돈'], ['pension', '연금']] as const).map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => onFilter(value)}>{label}</button>)}</div><div className="transaction-list">{visible.length ? visible.map(transaction => { const result = transaction.type === 'sell' ? saleResults.get(transaction.id) : undefined; return <article className="transaction-row" key={transaction.id}><div className="transaction-main"><time>{transaction.date.replaceAll('-', '.')}</time><b>{transaction.name} <span>{transaction.symbol}</span></b><p>{typeLabel(transaction.type)} {transaction.quantity.toLocaleString()}주 · {transaction.currency === 'USD' ? `$${transaction.price.toLocaleString('en-US')}` : `${transaction.price.toLocaleString('ko-KR')}원`}</p>{result && <small className={result.profit >= 0 ? 'up' : 'down'}>실현손익 {transaction.currency === 'USD' ? signedUsd(result.profit) : signedWon(result.profit)}</small>}{transaction.memo && <small>{transaction.memo}</small>}</div><div className="transaction-actions"><span>{typeLabel(transaction.type)}</span><button onClick={() => onEdit(transaction)} aria-label={`${transaction.name} 거래 수정`}><Pencil size={16} /></button><button className="danger-icon" onClick={() => onDelete(transaction)} aria-label={`${transaction.name} 거래 삭제`}><Trash2 size={16} /></button></div></article> }) : <p className="empty-ledger">아직 기록된 거래가 없습니다. 거래를 추가하면 보유수량과 실현손익을 자동으로 계산합니다.</p>}</div></section>
}
