import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './quote-status.css'
import './market.css'
import './transactions.css'
import './opening.css'
import './aggregate.css'
import './mobile.css'
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
